language: node_js
node_js:
  - "8.0"
  - "9.0"
  - "10.0"
install:
  - npm install -g codecov
  - npm ci
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov
