language: node_js
node_js:
  - "8.0"
  - "9.0"
  - "10.0"
install:
  - npm i -g npm@latest
  - npm install -g codecov
  - npm ci
script:
  - npm run test
  - codecov
after_success: npm run test-coverage
